/**************************************************************************
 * C S 429 system emulator
 *
 * instr_Decode.c - Decode stage of instruction processing pipeline.
 **************************************************************************/

#include <assert.h>
#include <stdbool.h>
#include <stdint.h>

#include "hw_elts.h"
#include "instr.h"
#include "instr_pipeline.h"

extern uint8_t D_src1, D_src2;

// LUT for extracting registers according to format.
extract_reg_func_t extract_regs_table[NUM_FORMATS];

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally.
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */
static comb_logic_t generate_DXMW_control(opcode_t op, d_ctl_sigs_t *D_sigs,
                                          x_ctl_sigs_t *X_sigs,
                                          m_ctl_sigs_t *M_sigs,
                                          w_ctl_sigs_t *W_sigs) {
    D_sigs->src2_sel = op == OP_STUR;
    X_sigs->vala_sel = op == OP_ADRP || op == OP_BL;
    X_sigs->valb_sel = op == OP_ADDS_RR || op == OP_CMN_RR || op == OP_SUBS_RR || op == OP_CMP_RR || op == OP_MVN || op == OP_ORR_RR || op == OP_EOR_RR || op == OP_ANDS_RR || op == OP_TST_RR || op == OP_LSL_RR || op == OP_LSR_RR || op == OP_UBFMV
#ifdef EC
                       || op == OP_CSEL || op == OP_CSINV || op == OP_CSINC ||
                       op == OP_CSNEG
#endif
        ;
    X_sigs->set_flags = op == OP_ADDS_RR || op == OP_CMN_RR || op == OP_SUBS_RR || op == OP_CMP_RR || op == OP_ANDS_RR || op == OP_TST_RR;
    M_sigs->dmem_read = op == OP_LDUR;
    M_sigs->dmem_write = op == OP_STUR;
    W_sigs->dst_sel = op == OP_BL;
    W_sigs->wval_sel = op == OP_LDUR;
    W_sigs->w_enable = op == OP_LDUR || op == OP_MOVK || op == OP_MOVZ || op == OP_ADRP || op == OP_ADD_RI || op == OP_ADDS_RR || op == OP_SUB_RI || op == OP_SUBS_RR || op == OP_MVN || op == OP_ORR_RR || op == OP_EOR_RR || op == OP_ANDS_RR || op == OP_LSL_RI || op == OP_LSR_RI || op == OP_UBFM || op == OP_LSL_RR || op == OP_LSR_RR || op == OP_UBFMV || op == OP_ASR || op == OP_BL
#ifdef EC
                      || op == OP_CSEL || op == OP_CSINV || op == OP_CSINC ||
                      op == OP_CSNEG || op == OP_BLR
#endif
        ;
    return;
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format
 * instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */
static comb_logic_t extract_immval(uint32_t insnbits, opcode_t op,
                                   int64_t *imm) {
    switch (op){
        case OP_ADD_RI:
        case OP_SUB_RI:
            *imm = bitfield_u32(insnbits, 10, 12);
            break;
        case OP_LSL_RI: {
            uint8_t immr = bitfield_u32(insnbits, 16, 6);
            *imm = 64 - immr;
            break;
        }
        case OP_LSR_RI:
            *imm = bitfield_u32(insnbits, 16, 6);
            break;
        case OP_ASR:
            *imm = bitfield_u32(insnbits, 16, 6);
            break;
        case OP_UBFM:
            *imm = bitfield_u32(insnbits, 10, 6);
            break;
        case OP_LDUR:
        case OP_STUR:
            *imm = bitfield_s64(insnbits, 12, 9);
            break;
        case OP_ADRP: {
            uint64_t immhi = bitfield_u32(insnbits, 5, 19);
            uint64_t immlo = bitfield_u32(insnbits, 29, 2);
            uint64_t imm21 = (immhi << 2) | immlo;
            *imm = ((int64_t)(imm21 << 43) >> 43) << 12;
            break;
        }
        case OP_B:
        case OP_BL:
            *imm = bitfield_s64(insnbits, 0, 26) << 2;
            break;
        case OP_B_COND:
            *imm = bitfield_s64(insnbits, 5, 19) << 2;
            break;
#ifdef EC
        case OP_CBZ:
        case OP_CBNZ:
            *imm = bitfield_s64(insnbits, 5, 19) << 2;
            break;
#endif
        case OP_MOVZ:
        case OP_MOVK: 
            *imm = bitfield_u32(insnbits, 5, 16);
            break;
        default:
            *imm = 0;
    }
    return;
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t decide_alu_op(opcode_t op, alu_op_t *ALU_op) {
    switch (op){
        case OP_LDUR:
        case OP_STUR:
        case OP_ADRP:
        case OP_ADD_RI:
        case OP_ADDS_RR:
        case OP_CMN_RR:
            *ALU_op = PLUS_OP;
            break;
        case OP_MOVK:
            *ALU_op = MOVK_OP;
            break;
        case OP_MOVZ:
            *ALU_op = MOV_OP;
            break;
        case OP_SUB_RI:
        case OP_SUBS_RR:
        case OP_CMP_RR:
            *ALU_op = MINUS_OP;
            break;
        case OP_MVN:
            *ALU_op = INV_OP;
            break;
        case OP_ORR_RR:
            *ALU_op = OR_OP;
            break;
        case OP_EOR_RR:
            *ALU_op = EOR_OP;
            break;
        case OP_ANDS_RR:
        case OP_TST_RR:
            *ALU_op = AND_OP;
            break;
        case OP_LSL_RI:
        case OP_UBFM:
        case OP_LSL_RR:
        case OP_UBFMV:
            *ALU_op = LSL_OP;
            break;
        case OP_LSR_RI:
        case OP_LSR_RR:
            *ALU_op = LSR_OP;
            break;
        case OP_ASR:
            *ALU_op = ASR_OP;
            break;
#ifdef EC
        case OP_CSEL:
            *ALU_op = CSEL_OP;
            break;
        case OP_CSINV:
            *ALU_op = CSINV_OP;
            break;
        case OP_CSINC:
            *ALU_op = CSINC_OP;
            break;
        case OP_CSNEG:
            *ALU_op = CSNEG_OP;
            break;
        case OP_CBZ:
            *ALU_op = CBZ_OP;
            break;
        case OP_CBNZ:
            *ALU_op = CBNZ_OP;
            break;
#endif
        default:
            *ALU_op = PASS_A_OP;
    }
    return;
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */
comb_logic_t copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src) {
    dest->dmem_read = src->dmem_read;
    dest->dmem_write = src->dmem_write;
    return;
}

comb_logic_t copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src) {
    dest->dst_sel = src->dst_sel;
    dest->w_enable = src->w_enable;
    dest->wval_sel = src->wval_sel;
    return;
}

/*
 * Utility functions for extracting src1, src2, and dst registers.
 * STUDENT TO-DO:
 * Update fix_regs to determine whether 31 represents SP or XZR.
 */
comb_logic_t fix_regs(opcode_t op, uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    if(*src2 == SP_NUM){
        *src2 = XZR_NUM;
    }
    switch (op){
        case OP_LDUR:
        case OP_STUR:
            if(*dst == SP_NUM){
                *dst = XZR_NUM;
            }
            break;
        case OP_ADD_RI:
        case OP_SUB_RI:
            break;
        default:
            if(*src1 == SP_NUM){
                *src1 = XZR_NUM;
            }
            if(*dst == SP_NUM){
                *dst = XZR_NUM;
            }
    }
    return;
}

/*
 * Extract src1, src2, and dst registers from instruction. Do not modify.
 */
comb_logic_t extract_regs(uint32_t insnbits, opcode_t op, format_t format,
                          uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    extract_regs_table[format](insnbits, op, src1, src2, dst);
    fix_regs(op, src1, src2, dst);
    return;
}

/*
 * Pass through for FORMAT_ERROR. Do not modify.
 */
comb_logic_t format_other(uint32_t insnbits, opcode_t op, uint8_t *src1,
                          uint8_t *src2, uint8_t *dst) {
    return;
}

/*
 * Extract registers for each instruction format.
 * STUDENT TO-DO:
 * Fill out. Remember that some formats may not require any work.
 */
comb_logic_t format_m(uint32_t insnbits, opcode_t op, uint8_t *src1,
                      uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    *dst = XZR_NUM;
    *src1 = bitfield_u32(insnbits, 5, 5);
    if (op == OP_STUR) {
        *src2 = bitfield_u32(insnbits, 0, 5);
    } else {
        *dst = bitfield_u32(insnbits, 0, 5);
    }
    return;
}

comb_logic_t format_i1(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    *dst = bitfield_u32(insnbits, 0, 5);
    if (op == OP_MOVK) {
        *src1 = *dst;
    }
    return;
}

comb_logic_t format_i2(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    *dst = bitfield_u32(insnbits, 0, 5);
    return;
}

comb_logic_t format_rr(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    *dst = XZR_NUM;
    *src1 = bitfield_u32(insnbits, 5, 5);
    *src2 = bitfield_u32(insnbits, 16, 5);
    *dst = bitfield_u32(insnbits, 0, 5);
    return;
}

comb_logic_t format_ri(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    *dst = bitfield_u32(insnbits, 0, 5);
    *src1 = bitfield_u32(insnbits, 5, 5);
    return;
}

comb_logic_t format_b1(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    if (op == OP_BL) {
        *dst = 30;
    } else {
        *dst = XZR_NUM;
    }
    return;
}

comb_logic_t format_b2(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    *dst = XZR_NUM;
    return;
}

comb_logic_t format_b3(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    *dst = XZR_NUM;
    *src1 = bitfield_u32(insnbits, 5, 5);
    return;
}

/* For NOP/HLT instructions.
 */
comb_logic_t format_s(uint32_t insnbits, opcode_t op, uint8_t *src1,
                      uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    *dst = XZR_NUM;
    return;
}

#ifdef EC
/*
 * Extra credit instructions.
 */
comb_logic_t format_ec(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    *src1 = XZR_NUM;
    *src2 = XZR_NUM;
    *dst = XZR_NUM;

    switch (op) {
        case OP_CSEL:
        case OP_CSINV:
        case OP_CSINC:
        case OP_CSNEG:
            *dst = bitfield_u32(insnbits, 0, 5);
            *src1 = bitfield_u32(insnbits, 5, 5);
            *src2 = bitfield_u32(insnbits, 16, 5);
            break;
        case OP_CBZ:
        case OP_CBNZ:
            *src1 = bitfield_u32(insnbits, 0, 5);
            break;
        case OP_BR:
        case OP_BLR:
            *src1 = bitfield_u32(insnbits, 5, 5);
            if (op == OP_BLR) {
                *dst = 30;
            }
            break;
        default:
            break;
    }
    return;
}
#endif

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 *
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 *
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval, extract_regs
 * and decide_alu_op.
 */
comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out) {
    opcode_t op = in->op;
    uint32_t insnbits = in->insnbits;
    // copy info
    out->op = op;
    out->print_op = in->print_op;
    out->multipurpose_val.seq_succ_PC = in->multipurpose_val.seq_succ_PC;
    out->status = in->status;

    // generate flags
    d_ctl_sigs_t D;
    x_ctl_sigs_t X;
    m_ctl_sigs_t M;
    w_ctl_sigs_t W;
    generate_DXMW_control(op, &D, &X, &M, &W);
    out->X_sigs = X;
    out->M_sigs = M;
    out->W_sigs = W;

    // extract regs
    uint8_t src1;
    uint8_t src2;
    uint8_t dest;
    extract_regs(insnbits, op, in->format, &src1, &src2, &dest);
    if(in->status == STAT_BUB || op == OP_NOP){
        out->val_a = 0;
        out->val_b = 0;
    } else{
        regfile_read(src1, src2, &out->val_a, &out->val_b);
    }
    out->dst = dest;
    D_src1 = src1;
    D_src2 = src2;

    // extract immediate
    extract_immval(insnbits, op, &out->val_imm);
#ifdef EC
    if (op == OP_BLR) {
        // BLR links X30 with the address of the instruction after BLR.
        out->val_imm = (int64_t) in->multipurpose_val.seq_succ_PC;
    }
#endif

    // choose ALU op
    decide_alu_op(op, &out->ALU_op);
    
    // val hw and cond
    out->val_hw = bitfield_u32(insnbits, 21, 2) << 4;
    if (op == OP_B_COND) {
        out->cond = bitfield_u32(insnbits, 0, 4);
#ifdef EC
    } else if (op == OP_CSEL || op == OP_CSINV || op == OP_CSINC ||
               op == OP_CSNEG) {
        out->cond = bitfield_u32(insnbits, 12, 4);      
#endif
    } else {
        out->cond = C_AL;
    }
    return;
}
